---
# Channel to use for the Red Hat Advanced Cluster Management for Kubernetes subscription
ocp4_workload_rhacm_acm_channel: release-2.14

# Set a starting ClusterServiceVersion.
# Recommended to leave empty to get latest in the channel when not using
# a catalog snapshot.
# Highly recommended to be set when using a catalog snapshot but can be
# empty to get the latest available in the channel at the time when
# the catalog snapshot got created.
# Match the first part of the CSV name to the nameprefix below
ocp4_workload_rhacm_acm_starting_csv: ""

# Set automatic InstallPlan approval. Must be set to false when specifying a starting_csv
ocp4_workload_rhacm_automatic_install_plan_approval: true

# This is used by the MultiClusterHub to install the multicluster-engine operator.
# Only set this under the following conditions:
# 1. ocp4_workload_rhacm_use_catalog_snapshot: false
# 2. In your cluster you have more than one catalogsource that provides the MCE operator.
ocp4_workload_rhacm_mce_catalogsource_name: ""

# This namespace cannot be changed due to multicluster-engine operator not able look elsewhere.
ocp4_workload_rhacm_mce_catalogsource_namespace: openshift-marketplace

# Required for Catalog Items that will deploy hosted clusters to the local-cluster
# Enable Wildcards to allow access to HCP Hosted Clusters console, etc.
ocp4_workload_rhacm_enable_wildcards: false

# --------------------------------
# Operator Catalog Snapshot Settings
# --------------------------------
# See https://github.com/redhat-cop/agnosticd/blob/development/docs/Operator_Catalog_Snapshots.adoc
# for instructions on how to set up catalog snapshot images
ocp4_workload_rhacm_use_catalog_snapshot: false
ocp4_workload_rhacm_catalogsource_name: catalogsource-rhacm
# This namespace cannot be changed due to multicluster-engine operator not able look elsewhere.
ocp4_workload_rhacm_catalogsource_namespace: openshift-marketplace
ocp4_workload_rhacm_catalog_source_image: ""
ocp4_workload_rhacm_catalog_source_tag: ""
