---
- name: Get DevSpaces route
  kubernetes.core.k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    name: devspaces
    namespace: "{{ ocp4_workload_devspaces_namespace }}"
  register: r_devspaces_route
  until: r_devspaces_route.resources | length > 0
  retries: 10
  delay: 5

- name: Set _ocp4_workload_devspaces_url
  ansible.builtin.set_fact:
    _ocp4_workload_devspaces_url: "https://{{ r_devspaces_route.resources[0].spec.host }}"

- name: Save DevSpaces URL (single user)
  when: ocp4_workload_devspaces_user_count is not defined
  agnosticd.core.agnosticd_user_info:
    data:
      devspaces_url: "{{ _ocp4_workload_devspaces_url }}"

- name: Save DevSpaces URL (multiple users)
  when: ocp4_workload_devspaces_user_count is defined
  agnosticd.core.agnosticd_user_info:
    user: "{{ ocp4_workload_devspaces_user_base }}{{ item }}"
    data:
      devspaces_url: "{{ _ocp4_workload_devspaces_url }}"
  loop: "{{ range(1, ocp4_workload_devspaces_user_count | int + 1) | list }}"
