---
- name: Remove stackrox namespace
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Namespace
    name: stackrox
  register: r_k8s
  until: r_k8s is successful
  retries: 30
  delay: 5

- name: Delete rbac
  ansible.builtin.shell: oc get clusterrole,clusterrolebinding,role,rolebinding,psp -o name | grep stackrox | xargs oc delete --wait

- name: Delete scc
  ansible.builtin.shell: oc delete scc -l "app.kubernetes.io/name=stackrox"

- name: Remove webhook
  kubernetes.core.k8s:
    state: absent
    api_versionersion: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    name: stackrox
  register: r_k8s
  until: r_k8s is successful
  retries: 30
  delay: 5

- name: remove all labels from all namespaces
  ansible.builtin.shell: >-
     for namespace in $(oc get ns | tail -n +2 | awk '{print $1}'); do
       oc label namespace $namespace namespace.metadata.stackrox.io/id-;
       oc label namespace $namespace namespace.metadata.stackrox.io/name-;
       oc annotate namespace $namespace modified-by.stackrox.io/namespace-label-patcher-;
     done

- name: Remove Operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_action: remove
    install_operator_name: rhacs-operator