---
- name: Delete the L2Advertisement instance
  when: ocp4_workload_metallb_enable_l2advertisement | default(false)
  kubernetes.core.k8s:
    state: absent
    template: l2advertisement.yaml.j2

- name: Delete the IPAddressPool instance
  when: ocp4_workload_metallb_enable_ipaddresspool | default(false)
  kubernetes.core.k8s:
    state: absent
    template: ipaddresspool.yaml.j2

- name: Delete MetalLB
  kubernetes.core.k8s:
    state: absent
    definition: "{{ lookup('file', 'metallb.yaml') }}"

- name: Remove MetalLB Operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_action: remove
    install_operator_name: metallb-operator
    install_operator_namespace: metallb-system
    install_operator_channel: "{{ ocp4_workload_metallb_channel }}"
    install_operator_catalog: redhat-operators
    install_operator_automatic_install_plan_approval: "{{ ocp4_workload_metallb_automatic_install_plan_approval | default(true) }}"
    install_operator_starting_csv: "{{ ocp4_workload_metallb_starting_csv }}"
    install_operator_catalogsource_setup: "{{ ocp4_workload_metallb_use_catalog_snapshot | default(false) }}"
    install_operator_catalogsource_name: "{{ ocp4_workload_metallb_catalogsource_name | default('') }}"
    install_operator_catalogsource_namespace: metallb-system
    install_operator_catalogsource_image: "{{ ocp4_workload_metallb_catalog_snapshot_image | default('') }}"
    install_operator_catalogsource_image_tag: "{{ ocp4_workload_metallb_catalog_snapshot_image_tag | default('') }}"
