---
- name: Install Elasticsearch operator
  when: ocp4_workload_servicemesh2_es | bool
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_name: elasticsearch-operator
    install_operator_namespace: openshift-operators-redhat
    install_operator_channel: "{{ ocp4_workload_servicemesh2_es_channel }}"
    install_operator_starting_csv: "{{ ocp4_workload_servicemesh2_es_startingcsv }}"
    install_operator_catalogsource_setup: "{{ ocp4_workload_servicemesh2_catalogsource_setup }}"
    install_operator_catalogsource_image: "{{ ocp4_workload_servicemesh2_catalogsource_image }}"
    install_operator_catalogsource_image_tag: "{{ ocp4_workload_servicemesh2_catalogsource_tag }}"

- name: Install Jaeger operator
  when: ocp4_workload_servicemesh2_jaeger | bool
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_name: jaeger-product
    install_operator_namespace: openshift-distributed-tracing
    install_operator_csv_nameprefix: jaeger-operator
    install_operator_channel: "{{ ocp4_workload_servicemesh2_jaeger_channel }}"
    install_operator_starting_csv: "{{ ocp4_workload_servicemesh2_jaeger_startingcsv }}"
    install_operator_catalogsource_setup: "{{ ocp4_workload_servicemesh2_catalogsource_setup }}"
    install_operator_catalogsource_image: "{{ ocp4_workload_servicemesh2_catalogsource_image }}"
    install_operator_catalogsource_image_tag: "{{ ocp4_workload_servicemesh2_catalogsource_tag }}"

- name: Install Kiali operator
  ansible.builtin.include_role:
    name: install_operator
  when: ocp4_workload_servicemesh2_kiali | bool
  vars:
    install_operator_name: kiali-ossm
    install_operator_namespace: openshift-operators
    install_operator_csv_nameprefix: kiali-operator
    install_operator_channel: "{{ ocp4_workload_servicemesh2_kiali_channel }}"
    install_operator_starting_csv: "{{ ocp4_workload_servicemesh2_kiali_startingcsv }}"
    install_operator_catalogsource_setup: "{{ ocp4_workload_servicemesh2_catalogsource_setup }}"
    install_operator_catalogsource_image: "{{ ocp4_workload_servicemesh2_catalogsource_image }}"
    install_operator_catalogsource_image_tag: "{{ ocp4_workload_servicemesh2_catalogsource_tag }}"

- name: Install Service Mesh 2 operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_name: servicemeshoperator
    install_operator_namespace: openshift-operators
    install_operator_channel: "{{ ocp4_workload_servicemesh2_servicemesh_channel }}"
    install_operator_starting_csv: "{{ ocp4_workload_servicemesh2_servicemesh_startingcsv }}"
    install_operator_catalogsource_setup: "{{ ocp4_workload_servicemesh2_catalogsource_setup }}"
    install_operator_catalogsource_image: "{{ ocp4_workload_servicemesh2_catalogsource_image }}"
    install_operator_catalogsource_image_tag: "{{ ocp4_workload_servicemesh2_catalogsource_tag }}"
