---
- name: Set disk name for {{ _vm_name }}
  ansible.builtin.set_fact:
    _dv_name: "{{ _disk_spec.name | replace('INSTANCENAME', _vm_name) }}"

- name: Remove volume {{ _dv_name }} from VM {{ _vm_name }}
  ansible.builtin.uri:
    url: >-
      {{ ocp4_workload_cnv_extra_disks_sandbox_api_url
      }}/apis/subresources.kubevirt.io/v1/namespaces/{{
      ocp4_workload_cnv_extra_disks_namespace
      }}/virtualmachineinstances/{{ _vm_name }}/removevolume
    method: PUT
    headers:
      Authorization: "Bearer {{ ocp4_workload_cnv_extra_disks_sandbox_api_key }}"
      Content-Type: "application/json"
    body_format: json
    body:
      name: "{{ _dv_name }}"
    validate_certs: false
    status_code: [200, 201]
  ignore_errors: true

- name: Delete DataVolume {{ _dv_name }}
  kubernetes.core.k8s:
    host: "{{ ocp4_workload_cnv_extra_disks_sandbox_api_url }}"
    api_key: "{{ ocp4_workload_cnv_extra_disks_sandbox_api_key }}"
    validate_certs: false
    state: absent
    api_version: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    name: "{{ _dv_name }}"
    namespace: "{{ ocp4_workload_cnv_extra_disks_namespace }}"