---
galaxy_info:
  role_name: ocp4_workload_garage
  author: Red Hat GPTE
  description: >-
    Deploy Garage S3-compatible distributed object storage on OpenShift using GitOps.
  license: MIT
  min_ansible_version: "2.9"
  platforms: []
  galaxy_tags:
  - ocp
  - openshift
  - s3
  - storage
  - gitops
  - argocd
  - garage
dependencies: []
