---
- name: Running workload tasks
  when: ACTION == "provision"
  ansible.builtin.include_tasks:
    file: workload.yml

- name: Running destroy tasks
  when: ACTION == "destroy"
  ansible.builtin.include_tasks:
    file: remove_workload.yml
