---
galaxy_info:
  role_name: ocp4_workload_authentication_htpasswd
  author: Red Hat, Wolfgang Kulhanek (wkulhane@redhat.com)
  description: |
    Set up htpasswd Authentication for OpenShift Container Platform.
  license: MIT
  min_ansible_version: "2.9"
  platforms: []
  galaxy_tags:
  - ocp
  - openshift
dependencies: []
