---
- name: Remove Quay Registry
  when: ocp4_workload_quay_operator_registry_install | bool
  block:
  - name: Remove Quay Registry
    kubernetes.core.k8s:
      state: absent
      api_version: quay.redhat.com/v1
      kind: QuayRegistry
      name: "{{ ocp4_workload_quay_operator_registry_name }}"
      namespace: "{{ ocp4_workload_quay_operator_registry_namespace }}"

  - name: Wait for all Quay Pods to be terminated
    kubernetes.core.k8s_info:
      api_version: v1
      kind: Pod
      namespace: "{{ ocp4_workload_quay_operator_registry_namespace }}"
      label_selectors:
      - "quay-operator/quayregistry = {{ ocp4_workload_quay_operator_registry_name }}"
    register: r_running_pods
    until: r_running_pods.resources | list | length == 0
    ignore_errors: true
    retries: 30
    delay: 10

  - name: Remove Quay Registry Namespace
    kubernetes.core.k8s:
      state: absent
      api_version: v1
      kind: Namespace
      name: "{{ ocp4_workload_quay_operator_registry_namespace }}"