---
galaxy_info:
  role_name: ocp4_workload_authentication_keycloak
  author: Demo Platform, Tyrell (treddy@redhat.com)
  description: |
    This role installs Keycloak Operator on OpenShift and configures it for authentication.
  license: MIT
  min_ansible_version: 2.9
  platforms: []
  galaxy_tags:
  - ocp
  - openshift
  - keycloak
dependencies: []
