---
- name: Install OpenShift NFD Operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_action: install
    install_operator_name: nfd-operator
    install_operator_namespace: "{{ ocp4_workload_nfd_operator_namespace }}"
    install_operator_channel: "{{ ocp4_workload_nfd_operator_channel }}"
    install_operator_catalog: redhat-operators
    install_operator_automatic_install_plan_approval: "{{ ocp4_workload_nfd_automatic_install_plan_approval }}"
    install_operator_starting_csv: "{{ ocp4_workload_nfd_starting_csv }}"
    install_operator_catalogsource_setup: "{{ ocp4_workload_nfd_use_catalog_snapshot }}"
    install_operator_catalogsource_name: "{{ ocp4_workload_nfd_catalogsource_name }}"
    install_operator_catalogsource_namespace: "{{ ocp4_workload_nfd_operator_namespace }}"
    install_operator_catalogsource_image: "{{ ocp4_workload_pipelines_catalog_snapshot_image | default('') }}"
    install_operator_catalogsource_image_tag: "{{ ocp4_workload_pipelines_catalog_snapshot_image_tag }}"

- name: Create NodeFeatureDiscovery Custom Resource
  kubernetes.core.k8s:
    state: present
    template: "nodefeature_discovery.yaml.j2"
  register: r_nfd
  until: r_nfd is not failed
  retries: 30
  delay: 20
