---
# - name: Remove the Kiali resource
#   kubernetes.core.k8s:
#     state: absent
#     template: kiali.yaml.j2

- name: Remove Kiali Operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_action: remove
    install_operator_name: kiali-ossm
    install_operator_csv_nameprefix: kiali-operator
    install_operator_namespace: openshift-operators
    install_operator_channel: "{{ ocp4_workload_kiali_channel }}"
    install_operator_automatic_install_plan_approval: "{{ ocp4_workload_kiali_automatic_install_plan_approval }}"
    install_operator_starting_csv: "{{ ocp4_workload_kiali_starting_csv }}"
    install_operator_catalogsource_setup: "{{ ocp4_workload_kiali_use_catalog_snapshot }}"
    install_operator_catalogsource_image: "{{ ocp4_workload_kiali_catalog_snapshot_image }}"
    install_operator_catalogsource_image_tag: "{{ ocp4_workload_kiali_catalog_snapshot_image_tag }}"
