---
- name: Install Kiali Operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_action: install
    install_operator_name: kiali-ossm
    install_operator_csv_nameprefix: kiali-operator
    install_operator_namespace: openshift-operators
    install_operator_channel: "{{ ocp4_workload_kiali_channel }}"
    install_operator_automatic_install_plan_approval: "{{ ocp4_workload_kiali_automatic_install_plan_approval }}"
    install_operator_starting_csv: "{{ ocp4_workload_kiali_starting_csv }}"
    install_operator_catalogsource_setup: "{{ ocp4_workload_kiali_use_catalog_snapshot }}"
    install_operator_catalogsource_image: "{{ ocp4_workload_kiali_catalog_snapshot_image }}"
    install_operator_catalogsource_image_tag: "{{ ocp4_workload_kiali_catalog_snapshot_image_tag }}"

- name: Create the Kiali RBAC
  kubernetes.core.k8s:
    state: present
    template: kiali-rbac.yaml.j2

- name: Create the Kiali resource
  kubernetes.core.k8s:
    state: present
    template: kiali.yaml.j2
    wait: true
    wait_condition:
      type: Successful
      status: "True"
    wait_timeout: 180

- name: Create the OSSMC plugin
  when: ocp4_workload_kiali_ossmconsole | bool
  kubernetes.core.k8s:
    state: present
    template: ossmconsole.yaml.j2

- name: Get the Kiali Route
  kubernetes.core.k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    name: kiali
    namespace: "{{ ocp4_workload_kiali_namespace }}"
  register: r_kiali_route
  failed_when: r_kiali_route.resources | default([]) | length != 1
  until: r_kiali_route is successful
  retries: 5
  delay: 10

- name: Save agnosticd user info
  block:
  - name: Print project information
    agnosticd.core.agnosticd_user_info:
      msg: "Kiali URL: https://{{ r_kiali_route.resources[0].spec.host }}"
      data:
        openshift_kiali_url: "https://{{ r_kiali_route.resources[0].spec.host }}"
