---
# Project where the MinIO service is deployed
ocp4_workload_minio_project: minio
ocp4_workload_minio_project_display: Minio Object Storage

# Name of the MinIO instance to set up
ocp4_workload_minio_name: minio

# Storage size for the MinIO persistent volume claim
ocp4_workload_minio_storage_size: "25Gi"
# Empty storage class means that the default storage class is used
ocp4_workload_minio_storage_class_name: ""

# Requests for the MinIO Pod
ocp4_workload_minio_requests_memory: 1Gi
ocp4_workload_minio_requests_cpu: 2

# Create Route objects for the MinIO Services
ocp4_workload_minio_expose_route: true

# Image for the MinIO Pod
ocp4_workload_minio_image: quay.io/minio/minio
# Don't use a later image - the license changed after 7/15/2025
ocp4_workload_minio_image_tag: RELEASE.2025-06-13T11-33-47Z

# Root credentials for MinIO
# Need to be set by the config
ocp4_workload_minio_root_user: ""
ocp4_workload_minio_root_password: ""
ocp4_workload_minio_root_policy: readwrite

# Create MinIO bucket(s) after installation
ocp4_workload_minio_bucket_setup: false

# Set up buckets for each user in a multi-user setup
ocp4_workload_minio_bucket_multi_user: false

# Single-user bucket names
ocp4_workload_minio_bucket_name:
- s3-storage

# Multi-User:
ocp4_workload_minio_bucket_base: s3-
ocp4_workload_minio_bucket_num_users: 1
ocp4_workload_minio_bucket_userbase: user
