---
# ==============================================================================
# AAP Platform Configuration
# This task file configures Ansible Automation Platform after installation
# Based on: ansible_automation_platform_configuration role from agnosticd
# ==============================================================================

- name: Generate OCP bearer token for use in AAP as OCP credential
  when: ocp4_workload_ansible_automation_platform_generate_ocp_token | bool
  ansible.builtin.include_tasks:
    file: configure_platform_ocp_token.yml

- name: Generate SSH keypair for use in AAP as ssh machine credential
  when: ocp4_workload_ansible_automation_platform_generate_ssh_keypair | bool
  ansible.builtin.include_tasks:
    file: configure_platform_ssh_keypair.yml

- name: Run AAP Configuration dispatcher
  when: ocp4_workload_ansible_automation_platform_run_dispatcher | bool
  ansible.builtin.include_tasks:
    file: configure_platform_dispatcher.yml
