---
# ==============================================================================
# AAP Configuration Dispatcher
# Uses infra.aap_configuration.dispatch to configure AAP resources
# ==============================================================================

- name: Create AAP2 resources
  environment:
    CONTROLLER_HOST: "{{ automation_controller_url }}"
    CONTROLLER_USERNAME: admin
    CONTROLLER_PASSWORD: "{{ _ocp4_workload_ansible_automation_platform_admin_password }}"
    CONTROLLER_VERIFY_SSL: "{{ ocp4_workload_ansible_automation_platform_verify_ssl }}"
  block:

    - name: Create AAP Controller token
      when: ocp4_workload_ansible_automation_platform_create_controller_token | bool
      block:
        - name: Create AAP Auth token
          ansible.controller.token:
            description: Creating token to configure AAP2 resources
            scope: write
            state: present
          register: r_aap_token
          until: r_aap_token.failed == false
          retries: 100
          delay: 30

        - name: Save token for agnosticd_user_info
          agnosticd.core.agnosticd_user_info:
            data:
              aap_controller_token: "{{ r_aap_token.ansible_facts.controller_token.token }}"

    - name: Run AAP Configuration dispatcher
      ansible.builtin.import_role:
        name: infra.aap_configuration.dispatch
