---
- name: Fetch Automation Controller manifest file
  ansible.builtin.get_url:
    url: "{{ ocp4_workload_ansible_automation_platform_manifest.url }}"
    dest: /tmp/aap-manifest.zip
    username: "{{ ocp4_workload_ansible_automation_platform_manifest.username | default(omit) }}"
    password: "{{ ocp4_workload_ansible_automation_platform_manifest.password | default(omit) }}"

- name: Inject AAP2 Controller manifest
  awx.awx.license:
    manifest: /tmp/aap-manifest.zip
    controller_host: "{{ automation_controller_hostname }}"
    controller_username: admin
    controller_password: "{{ _ocp4_workload_ansible_automation_platform_admin_password }}"
    validate_certs: true
  register: r_aap_license
  until: not r_aap_license.failed
  retries: 3
  delay: 5

- name: Remove AAP manifest
  ansible.builtin.file:
    path: /tmp/aap-manifest.zip
    state: absent
