---
- name: Prepare Variables
  ansible.builtin.include_tasks: prepare_variables.yaml

- name: Remove Namespace (single user)
  when: not _showroom_user_data.users is defined
  kubernetes.core.k8s:
    host: "{{ ocp4_workload_showroom_openshift_api_url | default(omit) }}"
    api_key: "{{ ocp4_workload_showroom_openshift_api_token | default(omit) }}"
    validate_certs: false
    state: absent
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ ocp4_workload_showroom_namespace }}"
  ignore_errors: true

- name: Remove Namespaces (multi user)
  when: _showroom_user_data.users is defined
  vars:
    _showroom_user: "{{ _showroom_users_item.key }}"
    _showroom_namespace: "{{ ocp4_workload_showroom_namespace }}-{{ _showroom_user }}"
  kubernetes.core.k8s:
    host: "{{ ocp4_workload_showroom_openshift_api_url | default(omit) }}"
    api_key: "{{ ocp4_workload_showroom_openshift_api_token | default(omit) }}"
    validate_certs: false
    state: absent
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ _showroom_namespace }}"
  ignore_errors: true
  loop: >-
    {{ _showroom_user_data.users | dict2items }}
  loop_control:
    loop_var: _showroom_users_item
    label: "{{ _showroom_users_item.key }}"
