---
- name: Get the Showroom route
  kubernetes.core.k8s_info:
    host: "{{ ocp4_workload_showroom_openshift_api_url | default(omit) }}"
    api_key: "{{ ocp4_workload_showroom_openshift_api_token | default(omit) }}"
    validate_certs: false
    api_version: route.openshift.io/v1
    kind: Route
    name: "{{ ocp4_workload_showroom_service_name }}"
    namespace: "{{ _showroom_namespace }}"
  register: r_showroom_route
  failed_when: r_showroom_route.resources | default([]) | length != 1
  until: r_showroom_route is successful
  retries: 100
  delay: 5

- name: Output agnosticd_user_data for showroom
  vars:
    _showroom_url: "https://{{ r_showroom_route.resources[0].spec.host }}/"
  agnosticd.core.agnosticd_user_info:
    msg: "Lab instructions: {{ _showroom_url }}"
    data:
      showroom_primary_view_url: "{{ _showroom_url }}"
    user: "{{ _showroom_user | default(omit) }}"
