---
galaxy_info:
  role_name: ocp4_workload_servicemesh3
  author: Red Hat, Juliano Mohr (juliano@redhat.com)
  description: |
    Set up Red Hat OpenShift Service Mesh 3 on OpenShift.
  license: MIT
  min_ansible_version: "2.9"
  platforms: []
  galaxy_tags:
  - ocp
  - openshift
  - servicemesh
  - istio
  - ossm
dependencies: []
