---
galaxy_info:
  role_name: ocp4_workload_nfd
  author: Red Hat, Wolfgang Kulhanek (wkulhane@redhat.com)
  description: |
    Set up OpenShift NFD Operator.
  license: MIT
  min_ansible_version: 2.9
  platforms: []
  galaxy_tags:
  - ocp
  - openshift
dependencies: []
