---
# defaults for _showroom_user_data so env destroys don't fail
_showroom_user_data:
  bastion_public_hostname: 'test_hostname'
  bastion_ssh_password: 'test_password'
  bastion_ssh_user_name: 'test_user_name'
