---
- name: Use provided HostedZoneID
  when: ocp4_workload_cert_manager_aws_hostedzoneid | default("") | length > 0
  ansible.builtin.set_fact:
    _ocp4_workload_cert_manager_hostedzoneid: >-
      {{ ocp4_workload_cert_manager_aws_hostedzoneid }}

- name: Determine HostedZoneID
  when: ocp4_workload_cert_manager_aws_hostedzoneid | default("") | length == 0
  block:
  - name: Get HostedZoneID
    kubernetes.core.k8s_info:
      api_version: config.openshift.io/v1
      kind: DNS
      name: cluster
    register: r_hostedzoneid
    retries: 5
    delay: 5
    until:
    - r_hostedzoneid.resources is defined
    - r_hostedzoneid.resources | length > 0
    - r_hostedzoneid.resources[0].spec.publicZone.id is defined

  - name: Debug HostedZoneID result
    ansible.builtin.debug:
      msg: "{{ r_hostedzoneid }}"

  - name: Set HostedZoneID fact
    ansible.builtin.set_fact:
      _ocp4_workload_cert_manager_hostedzoneid: >-
        {{ r_hostedzoneid.resources[0].spec.publicZone.id }}

- name: Print HostedZoneID
  ansible.builtin.debug:
    msg: >-
      HostedZoneID: {{ _ocp4_workload_cert_manager_hostedzoneid }}

- name: Create AWS credentials secret for cert manager
  kubernetes.core.k8s:
    state: present
    template: secret-aws-credentials.yaml.j2
